---
- name: Run through Hardware Checks
  when: tpm_enable_hardware_checks
  include_tasks: tpm_hardware_check.yml

- name: Call tasks to setup the TPM Simulator
  when: tpm_simulator_install
  include_tasks: tpm_setup_simulator.yml

- name: Call tasks to install and configure tpm2-tss
  include_tasks: tpm_tss_setup.yml

- name: Call tasks to install and configure tpm2-abrmd
  include_tasks: tpm_abrmd_setup.yml

- name: Call tasks to install and configure tpm2-tools
  include_tasks: tpm_tools_setup.yml