---
- name: Install openssl-devel, make and gcc
  yum:
    name:
      - openssl-devel
      - make
      - gcc
    state: present

- name: Download TPM Simulator
  shell: |
    wget https://sourceforge.net/projects/ibmswtpm2/files/{{ tpm_simulator_package }}/download -O /tmp/{{ tpm_simulator_package }}
  args:
    creates: "/tmp/{{ tpm_simulator_package }}"

- name: Ensure opt directory for tpm2-simulator
  file:
    state: directory
    path: "/opt/tpm2-simulator"

- name: Unarchive content
  unarchive:
    src: "/tmp/{{ tpm_simulator_package }}"
    dest: "/opt/tpm2-simulator"
    remote_src: true

- name: Make from source
  shell: |
    make
  args:
    creates: "/opt/tpm2-simulator/src/tpm_server"
    chdir: "/opt/tpm2-simulator/src"

- name: Move tpm_server
  file:
    src: /opt/tpm2-simulator/src/tpm_server
    path: /usr/local/bin/tpm_server
    owner: root
    group: root
    state: link
    force: yes